const genreArtists = {
  pop: [
    "taylor swift",
    "the weeknd",
    "sabrina carpenter",
    "justin bieber",
    "billie eilish",
    "ariana grande",
    "rihanna",
    "bruno mars",
    "tate mcrae",
    "lady gaga",
    "olivia rodrigo",
    "dua lipa",
    "maroon 5",
    "beyoncé",
    "adele",
    "katy perry",
    "charli xcx",
    "teddy swims",
    "sia",
    "miley cyrus",
    "halsey",
    "harry styles",
    "lorde",
    "britney spears",
    "charlie puth",
    "shawn mendes",
    "sam smith",
    "olivia dean",
    "cigarettes after sex",
    "the marias",
    "one direction",
    "frank ocean",
    "chappell roan",
    "gracie abrams",
    "raye",
    "noah kahan",
    "lauv",
    "the kid laroi",
    "carly rae jepsen",
  ],
  "hip-hop": [
    "bad bunny",
    "drake",
    "travis scott",
    "kanye west",
    "kendrick lamar",
    "eminem",
    "post malone",
    "future",
    "tyler the creator",
    "playboi carti",
    "youngboy never broke again",
    "gunna",
    "juice wrld",
    "21 savage",
    "lil baby",
    "lil wayne",
    "lil peep",
    "50 cent",
    "asap rocky",
    "cardi b",
    "mac miller",
    "lil uzi vert",
    "young thug",
    "bryson tiller",
    "nicki minaj",
    "wisin & yandel",
    "arcángel",
    "don toliver",
    "metro boomin",
    "partynextdoor",
    "suicideboy$",
    "blessd",
    "omar courtz",
  ],
  rock: [
    "coldplay",
    "linkin park",
    "radiohead",
    "imagine dragons",
    "arctic monkeys",
    "red hot chili peppers",
    "queen",
    "the beatles",
    "nirvana",
    "metallica",
    "deftones",
    "system of a down",
    "green day",
    "oasis",
    "ac/dc",
    "guns n' roses",
    "foo fighters",
    "the neighbourhood",
    "twenty one pilots",
    "fleetwood mac",
    "the strokes",
    "tame impala",
    "gorillaz",
    "portugal. the man",
    "foster the people",
    "cage the elephant",
    "vampire weekend",
    "alt-j",
    "mgmt",
    "the shins",
    "broken bells",
    "glass animals",
    "kings of leon",
    "muse",
    "paramore",
    "fall out boy",
    "my chemical romance",
    "panic! at the disco",
    "the killers",
    "the black keys",
    "arcade fire",
    "florence + the machine",
    "the lumineers",
    "mumford & sons",
    "of monsters and men",
    "bon iver",
    "the national",
    "interpol",
    "the white stripes",
    "jack white",
    "the raconteurs",
    "death cab for cutie",
    "the smashing pumpkins",
    "soundgarden",
    "pearl jam",
    "alice in chains",
    "stone temple pilots",
    "tool",
    "a perfect circle",
    "nine inch nails",
    "the cure",
    "the smiths",
    "joy division",
    "new order",
    "pixies",
    "dinosaur jr.",
    "sonic youth",
    "weezer",
    "blink-182",
    "sum 41",
    "good charlotte",
    "simple plan",
    "the offspring",
    "ramones",
    "the clash",
    "sex pistols",
    "the rolling stones",
    "led zeppelin",
    "pink floyd",
    "the who",
    "deep purple",
    "black sabbath",
    "iron maiden",
    "judas priest",
    "motorhead",
    "slipknot",
    "korn",
    "limp bizkit",
    "evanescence",
    "within temptation",
    "nightwish",
    "apocalyptica",
    "five finger death punch",
    "avenged sevenfold",
    "breaking benjamin",
    "three days grace",
    "shinedown",
    "shadows fall",
    "killswitch engage",
    "bullet for my valentine",
    "bring me the horizon",
    "parkway drive",
    "architects",
    "while she sleeps",
  ],
  latin: [
    "fuerza regida",
    "rauw alejandro",
    "junior h",
    "peso pluma",
    "j balvin",
    "feid",
    "anuel aa",
    "tito double p",
    "natanael cano",
    "ozuna",
    "daddy yon",
    "shakira",
    "manuel turizo",
    "cris mj",
    "danny ocean",
    "farruko",
    "banda ms de sergio lizárraga",
    "grupo firme",
    "duki",
    "grupo frontera",
    "carín león",
    "victor mendivil",
    "neton vega",
    "henrique & juliano",
    "oscar maydon",
    "luis r conriquez",
    "la arrolladora banda el limón de rene camacho",
    "mora",
  ],
  rnb: [
    "sza",
    "chris brown",
    "daniel caesar",
    "kali uchis",
    "the weeknd",
    "bryson tiller",
    "partynextdoor",
    "frank ocean",
    "snoh aalegra",
    "summer walker",
    "jhene aiko",
    "dvsn",
  ],
  electronic: [
    "david guetta",
    "calvin harris",
    "the chainsmokers",
    "kygo",
    "marshmello",
    "alesso",
    "zedd",
    "diplo",
    "ovy on the drums",
    "major lazer",
    "disclosure",
  ],
  kpop: [
    "bts",
    "kpop demon hunters cast",
    "stray kids",
    "twice",
    "blackpink",
    "jennie",
    "jin",
    "newjeans",
    "ive",
    "itzy",
    "enhypen",
    "txt",
    "aespa",
    "exo",
    "red velvet",
  ],
  country: [
    "morgan wallen",
    "luke combs",
    "zach bryan",
    "chris stapleton",
    "blake shelton",
    "kane brown",
    "jason aldean",
    "thomas rhett",
    "carrie underwood",
    "miranda lambert",
    "luke bryan",
  ],
  indie: [
    "tame impala",
    "lana del rey",
    "hozier",
    "phoebe bridgers",
    "bon iver",
    "fleet foxes",
    "the national",
    "arcade fire",
    "vampire weekend",
    "florence + the machine",
    "beabadoobee",
  ],
  bollywood: [
    "arijit singh",
    "pritam",
    "shreya ghoshal",
    "a.r. rahman",
    "anirudh ravichander",
    "alka yagnik",
    "shreya ghoshal",
    "udit narayan",
    "sachin-jigar",
    "tanishk bagchi",
    "vishal-shekhar",
    "amitabh bhattacharya",
    "irshad kamil",
    "s.p. balasubrahmanyam",
    "atif aslam",
    "karan aujla",
  ],
  alternative: [
    "gorillaz",
    "portugal. the man",
    "foster the people",
    "cage the elephant",
    "vampire weekend",
    "alt-j",
    "mgmt",
    "the shins",
    "broken bells",
    "glass animals",
  ],
};
